### ISSUE TITLE
`nanoserver/cmd/mahjong/web/service/login/login.go`中依赖能改一下吗？

### ISSUE THREAD

**Issue by frankiezdh** [lonnng/nanoserver#7]
[这行](https://github.com/lonnng/nanoserver/blob/82f1101e7e0220dcf3f3e269a49029ddd603ac7f/cmd/mahjong/web/service/login/login.go#L16) 依赖能改一下吗？

参照[链接](https://github.com/chanxuehong/wechat.v2)，现在已经修改成 

```
gopkg.in/chanxuehong/wechat.v2
```

**Comment by lonnng** [comment]
可以, 如果方便, 你提交PR, 我Merge

**Comment by frankiezdh** [comment]
您能直接改一下吗？PR吭哧吭哧太慢了。顺便把vendor删一下，直接使用go mod吧

**Comment by lonnng** [comment]
go mod有些人拉不下来x包

**Comment by lonnng** [comment]
@frankiezdh 如果你急用, 你先在你本地改了用嘛, 我有时间了改一下

**Comment by frankiezdh** [comment]
@lonnng 不急。谢谢~~  

go mod 支持replace，可以不用翻墙使用golang.org/x

**Comment by lonnng** [comment]
更新一下, https://github.com/lonnng/nanoserver/commit/5c64346f00543a2bc421b4837e38e56937a66b5a

**Comment by frankiezdh** [comment]
谢谢
